version: '3'

services:
  php:
    image: docker.io/bitnami/php-fpm:8.2
    container_name: insys-php_cnt
    networks:
      - insys_net
    resource_limits:
      memory: 512m  # 512MB mem limit
      cpus: 0.5     # 50% CPU limit
    depends_on: mysql
    command: tail -f /dev/null  # keeps alive
  mysql:
    image: docker.io/library/mysql:8.0-debian
    container_name: insys-mysql_cnt
    environment:
      - MYSQL_ROOT_PASSWORD=rot
    networks:
      - insys_net
    ports:
      - "127.0.0.1:3310:3306"
    volumes:
      - insys-mysql_vol:/var/lib/mysql
    resource_limits:
      memory: 256m
      cpus: 0.3

networks:
  insys_net:
    driver: bridge

volumes:
  insys-mysql_vol:
    driver: local
