version: '3'

services:
  python:
    build:
      context: .
      dockerfile: python-df
    image: localhost/univ6-python:3.10
    networks:   # lets containers on local machine communicate using their names (no LAN/WAN exposure)
      - backend
    resource_limits:
      memory: 1024m  # 1024MB mem limit
      cpus: 0.6     # 60% CPU limit
    command: tail -f /dev/null  # keeps alive
  dotnet:
    build:
      context: .
      dockerfile: dotnet-df
    image: localhost/univ6-dotnet:8.0
    networks:
      - backend
    resource_limits:
      memory: 1024m
      cpus: 0.7
    command: tail -f /dev/null

networks:
  backend:
    driver: bridge
