version: '3.8'

services:
  db:
    image: docker.io/library/mongo:8.0-noble
    container_name: insys-mongo-db_cnt
    ports:
      - "127.0.0.1:27018:27017" #to prevent port conflicts
    volumes:
      - mongo_data:/data/db
      - ./df/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - insys-net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: df/nj-dev_df
    image: insys/simple-nodejs:never
    container_name: insys-nj-app_cnt
    volumes:
      - .:/home/app
    ports:
      - "127.0.0.1:3004:3004"
    tty: true
    stdin_open: true
    networks:
      - insys-net
    depends_on:
      db:
        condition: service_healthy

networks:
  insys-net:
    driver: bridge

volumes:
  mongo_data:
